const mongoose = require("mongoose");
const Stock = require("../models/Stock");
const Indice = require("../models/Indices");
const config = require("../config/config");

const connectDb = async () => {
  try {
    await mongoose.connect(config.mongo_uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("MongoDB Connected");
  } catch (err) {
    console.error("DB connection error:", err.message);
    process.exit(1);
  }
};

const seedData = async () => {
  await connectDb();

  // Stocks
  const stocks = [
    {
      symbol: "RELIANCE.NS",
      name: "Reliance Industries",
      currentPrice: 2500,
      lastPrice: 2500,
      openPrice: 2500,
      closePrice: 2500,
      dayHigh: 2500,
      dayLow: 2500,
      availableShares: 700,
    },
    {
      symbol: "HDFCBANK.NS",
      name: "HDFC Bank",
      currentPrice: 1600,
      lastPrice: 1600,
      openPrice: 1600,
      closePrice: 1600,
      dayHigh: 1600,
      dayLow: 1600,
      availableShares: 500,
    },
    {
      symbol: "INFY.NS",
      name: "Infosys Ltd",
      currentPrice: 1458.5,
      lastPrice: 1458,
      openPrice: 1458,
      closePrice: 1458,
      dayHigh: 1458,
      dayLow: 1458,
      availableShares: 300,
    },
    {
      symbol: "SBIN.NS",
      name: "State Bank of India",
      currentPrice: 864.7,
      lastPrice: 864,
      openPrice: 864,
      closePrice: 864,
      dayHigh: 864,
      dayLow: 864,
      availableShares: 300,
    },
    {
      symbol: "ICICIBANK.NS",
      name: "ICICI Bank Ltd",
      currentPrice: 1375.9,
      lastPrice: 1375,
      openPrice: 1375,
      closePrice: 1375,
      dayHigh: 1375,
      dayLow: 1375,
      availableShares: 400,
    },
    {
      symbol: "TCS.NS",
      name: "Tata Consultancy Services Ltd",
      currentPrice: 3031.5,
      lastPrice: 3031,
      openPrice: 3031,
      closePrice: 3031,
      dayHigh: 3031,
      dayLow: 3031,
      availableShares: 700,
    },
    {
      symbol: "KOTAKBANK.NS",
      name: "Kotak Mahindra Bank Ltd",
      currentPrice: 1216.5,
      lastPrice: 1216,
      openPrice: 1216,
      closePrice: 1216,
      dayHigh: 1216,
      dayLow: 1216,
      availableShares: 500,
    },
    {
      symbol: "HINDUNILVR.NS",
      name: "Hindustan Unilever Ltd",
      currentPrice: 130,
      lastPrice: 130,
      openPrice: 130,
      closePrice: 130,
      dayHigh: 130,
      dayLow: 130,
      availableShares: 400,
    },
    {
      symbol: "BAJFINANCE.NS",
      name: "Bajaj Finance Ltd",
      currentPrice: 700.5,
      lastPrice: 700,
      openPrice: 700,
      closePrice: 700,
      dayHigh: 700,
      dayLow: 700,
      availableShares: 500,
    },
    {
      symbol: "LT.NS",
      name: "Larsen & Toubro Ltd",
      currentPrice: 1200.23,
      lastPrice: 1200,
      openPrice: 1200,
      closePrice: 1200,
      dayHigh: 1200,
      dayLow: 1200,
      availableShares: 600,
    },
    {
      symbol: "AXISBANK.NS",
      name: "Axis Bank Ltd",
      currentPrice: 550.56,
      lastPrice: 550,
      openPrice: 550,
      closePrice: 550,
      dayHigh: 550,
      dayLow: 550,
      availableShares: 500,
    },
    {
      symbol: "MARUTI.NS",
      name: "Maruti Suzuki India Ltd",
      currentPrice: 3000.56,
      lastPrice: 3000,
      openPrice: 3000,
      closePrice: 3000,
      dayHigh: 3000,
      dayLow: 3000,
      availableShares: 700,
    },
    {
      symbol: "TATASTEEL.NS",
      name: "Tata Steel Ltd",
      currentPrice: 2300.56,
      lastPrice: 2300,
      openPrice: 2300,
      closePrice: 2300,
      dayHigh: 2300,
      dayLow: 2300,
      availableShares: 500,
    },
    {
      symbol: "SUNPHARMA.NS",
      name: "Sun Pharmaceutical Industries Ltd",
      currentPrice: 4500,
      lastPrice: 4500,
      openPrice: 4500,
      closePrice: 4500,
      dayHigh: 4500,
      dayLow: 4500,
      availableShares: 300,
    },
    {
      symbol: "HCLTECH.NS",
      name: "HCL Technologies Ltd",
      currentPrice: 1843.89,
      lastPrice: 1843,
      openPrice: 1843,
      closePrice: 1843,
      dayHigh: 1843,
      dayLow: 1843,
      availableShares: 500,
    },
    {
      symbol: "WIPRO.NS",
      name: "Wipro Ltd",
      currentPrice: 890.5,
      lastPrice: 890,
      openPrice: 890,
      closePrice: 890,
      dayHigh: 890,
      dayLow: 890,
      availableShares: 500,
    },
    {
      symbol: "NESTLEIND.NS",
      name: "Nestlé India Ltd",
      currentPrice: 1680.78,
      lastPrice: 1680,
      openPrice: 1680,
      closePrice: 1680,
      dayHigh: 1680,
      dayLow: 1680,
      availableShares: 500,
    },
    {
      symbol: "ULTRACEMCO.NS",
      name: "UltraTech Cement Ltd",
      currentPrice: 2700,
      lastPrice: 2700,
      openPrice: 2700,
      closePrice: 2700,
      dayHigh: 2700,
      dayLow: 2700,
      availableShares: 800,
    },
    {
      symbol: "POWERGRID.NS",
      name: "POWERGRID.NS",
      currentPrice: 3476.51,
      lastPrice: 3476,
      openPrice: 3476,
      closePrice: 3476,
      dayHigh: 3476,
      dayLow: 3476,
      availableShares: 500,
    },
    {
      symbol: "ONGC.NS",
      name: "Oil & Natural Gas Corporation Ltd",
      currentPrice: 1600.67,
      lastPrice: 1600,
      openPrice: 1600,
      closePrice: 1600,
      dayHigh: 1600,
      dayLow: 1600,
      availableShares: 500,
    },
    {
      symbol: "TITAN.NS",
      name: "Titan Company Ltd",
      currentPrice: 6100.54,
      lastPrice: 6100,
      openPrice: 6100,
      closePrice: 6100,
      dayHigh: 6100,
      dayLow: 6100,
      availableShares: 200,
    },
    {
      symbol: "TATAMOTORS.NS",
      name: "Tata Motors Ltd",
      currentPrice: 680.41,
      lastPrice: 680,
      openPrice: 680,
      closePrice: 680,
      dayHigh: 680,
      dayLow: 680,
      availableShares: 500,
    },
    {
      symbol: "GRASIM.NS",
      name: "Grasim Industries Ltd",
      currentPrice: 1700.56,
      lastPrice: 1700,
      openPrice: 1700,
      closePrice: 1700,
      dayHigh: 1700,
      dayLow: 1700,
      availableShares: 500,
    },
    {
      symbol: "CIPLA.NS",
      name: "Cipla Ltd",
      currentPrice: 2600.54,
      lastPrice: 2600,
      openPrice: 2600,
      closePrice: 2600,
      dayHigh: 2600,
      dayLow: 2600,
      availableShares: 500,
    },
    {
      symbol: "ADANIENT.NS",
      name: "Adani Enterprises Ltd",
      currentPrice: 3400,
      lastPrice: 3400,
      openPrice: 3400,
      closePrice: 3400,
      dayHigh: 3400,
      dayLow: 3400,
      availableShares: 500,
    },
    {
      symbol: "ADANIPORTS.NS",
      name: "Adani Ports & SEZ Ltd",
      currentPrice: 2145.56,
      lastPrice: 2145,
      openPrice: 2145,
      closePrice: 2145,
      dayHigh: 2145,
      dayLow: 2145,
      availableShares: 500,
    },
    {
      symbol: "COALINDIA.NS",
      name: "Coal India Ltd",
      currentPrice: 3100.63,
      lastPrice: 3100,
      openPrice: 3100,
      closePrice: 3100,
      dayHigh: 3100,
      dayLow: 3100,
      availableShares: 500,
    },
    {
      symbol: "EICHERMOT.NS",
      name: "Eicher Motors Ltd",
      currentPrice: 1500.38,
      lastPrice: 1500,
      openPrice: 1500,
      closePrice: 1500,
      dayHigh: 1500,
      dayLow: 1500,
      availableShares: 500,
    },
    {
      symbol: "HINDALCO.NS",
      name: "Hindalco Industries Ltd",
      currentPrice: 200.56,
      lastPrice: 200,
      openPrice: 200,
      closePrice: 200,
      dayHigh: 200,
      dayLow: 200,
      availableShares: 500,
    },
  ];

  const indices = [
    { symbol: "NIFTY50", name: "Nifty 50", value: 20000 },
    { symbol: "SENSEX", name: "BSE Sensex", value: 65000 },
  ];

  try {
    await Stock.deleteMany({});
    await Indice.deleteMany({});
    await Stock.insertMany(stocks);
    await Indice.insertMany(indices);
    console.log("Dummy data inserted ✅");
  } catch (err) {
    console.error("Seeding error:", err);
  } finally {
    mongoose.connection.close();
  }
};

seedData();
